# Generated by Django 5.2.7 on 2025-10-28 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('html_template', models.TextField(verbose_name='Plantilla HTML')),
                ('css_styles', models.TextField(blank=True, verbose_name='Estilos CSS')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='Imagen de fondo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por defecto')),
                ('field_positions', models.JSONField(default=dict, verbose_name='Posiciones de campos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Certificado',
                'verbose_name_plural': 'Plantillas de Certificados',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre del evento')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'DNI debe tener 8 dígitos numéricos')], verbose_name='DNI')),
                ('full_name', models.CharField(max_length=300, verbose_name='Nombres y Apellidos')),
                ('attendee_type', models.CharField(choices=[('ASISTENTE', 'Asistente'), ('PONENTE', 'Ponente'), ('ORGANIZADOR', 'Organizador')], max_length=20, verbose_name='Tipo de Asistente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='certificates.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('pdf_file', models.FileField(upload_to='certificates/%Y/%m/', verbose_name='Archivo PDF')),
                ('qr_code', models.ImageField(upload_to='qr_codes/%Y/%m/', verbose_name='Código QR')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado el')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Firmado digitalmente')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Firmado el')),
                ('verification_url', models.URLField(verbose_name='URL de verificación')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='certificates.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('IMPORT', 'Importación Excel'), ('GENERATE', 'Generación Certificado'), ('SIGN', 'Firma Digital'), ('QUERY', 'Consulta DNI'), ('VERIFY', 'Verificación QR')], db_index=True, max_length=20, verbose_name='Tipo de acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='certificate_timesta_fc34eb_idx'), models.Index(fields=['action_type'], name='certificate_action__e811ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['dni'], name='certificate_dni_3ac524_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['dni', 'event'], name='certificate_dni_d8cd05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('dni', 'event')},
        ),
    ]
