# Generated by Django 5.2.7 on 2025-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='external_system',
            field=models.CharField(blank=True, help_text='Nombre del sistema del que proviene el certificado', max_length=200, verbose_name='Sistema Externo'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL del certificado en el sistema externo', max_length=500, verbose_name='URL Externa'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Indica si el certificado fue importado de un sistema externo', verbose_name='Certificado Externo'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_url',
            field=models.URLField(blank=True, verbose_name='URL de verificación'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_external'], name='certificate_is_exte_140671_idx'),
        ),
    ]
