# Generated by Django 5.2.7 on 2025-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_external_system_certificate_external_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['generated_at'], name='certificate_generat_6a49ec_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_signed'], name='certificate_is_sign_581e15_idx'),
        ),
    ]
