# Generated by Django 5.2.7 on 2025-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_certificate_generat_6a49ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='exported_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se exportó para firma', null=True, verbose_name='Exportado el'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_imported_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se importó la versión firmada final', null=True, verbose_name='Importado Final el'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_pdf',
            field=models.FileField(blank=True, help_text='PDF firmado final (para preview público)', null=True, upload_to='certificates/final/%Y/%m/', verbose_name='PDF Final Firmado'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='original_pdf',
            field=models.FileField(blank=True, help_text='PDF original sin QR', null=True, upload_to='certificates/original/%Y/%m/', verbose_name='PDF Original'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se procesó el QR', null=True, verbose_name='Procesado el'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='processing_errors',
            field=models.TextField(blank=True, help_text='Errores ocurridos durante el procesamiento', verbose_name='Errores de Procesamiento'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('IMPORTED', 'Importado (sin QR)'), ('QR_GENERATED', 'QR Generado'), ('QR_INSERTED', 'QR Insertado en PDF'), ('EXPORTED_FOR_SIGNING', 'Exportado para Firma'), ('SIGNED_FINAL', 'Firmado Final'), ('ERROR', 'Error en Procesamiento')], default='IMPORTED', help_text='Estado actual del procesamiento del certificado', max_length=50, verbose_name='Estado de Procesamiento'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_image',
            field=models.FileField(blank=True, help_text='Imagen del código QR generado', null=True, upload_to='certificates/qr_codes/%Y/%m/', verbose_name='Imagen QR'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_pdf',
            field=models.FileField(blank=True, help_text='PDF con QR insertado (listo para firma)', null=True, upload_to='certificates/with_qr/%Y/%m/', verbose_name='PDF con QR'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_position_x',
            field=models.IntegerField(default=450, help_text='Posición X del QR en el PDF (píxeles desde la izquierda)', verbose_name='Posición X del QR'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_position_y',
            field=models.IntegerField(default=50, help_text='Posición Y del QR en el PDF (píxeles desde arriba)', verbose_name='Posición Y del QR'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_size',
            field=models.IntegerField(default=100, help_text='Tamaño del código QR en píxeles', verbose_name='Tamaño del QR'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['processing_status'], name='certificate_process_b76306_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['processed_at'], name='certificate_process_1fd3e7_idx'),
        ),
    ]
