# Generated by Django 5.2.7 on 2025-10-31 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_exported_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre identificador de esta configuración', max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('default_qr_x', models.IntegerField(default=450, help_text='Posición X del QR en píxeles desde la izquierda del PDF', verbose_name='Posición X por Defecto')),
                ('default_qr_y', models.IntegerField(default=50, help_text='Posición Y del QR en píxeles desde arriba del PDF', verbose_name='Posición Y por Defecto')),
                ('default_qr_size', models.IntegerField(default=100, help_text='Tamaño del código QR en píxeles', verbose_name='Tamaño por Defecto')),
                ('qr_error_correction', models.CharField(choices=[('L', 'Low (7%)'), ('M', 'Medium (15%)'), ('Q', 'Quartile (25%)'), ('H', 'High (30%)')], default='M', help_text='Nivel de corrección de errores del código QR', max_length=1, verbose_name='Corrección de Errores')),
                ('qr_border', models.IntegerField(default=2, help_text='Tamaño del borde blanco alrededor del QR (en módulos)', verbose_name='Borde del QR')),
                ('qr_box_size', models.IntegerField(default=10, help_text='Tamaño de cada caja/módulo del QR en píxeles', verbose_name='Tamaño de Caja')),
                ('preview_base_url', models.URLField(default='http://localhost:8000', help_text='URL base que se usará en los códigos QR para preview de certificados', max_length=500, verbose_name='URL Base para Preview')),
                ('enable_qr_validation', models.BooleanField(default=True, help_text='Validar que el QR generado sea legible antes de insertarlo', verbose_name='Habilitar Validación de QR')),
                ('enable_pdf_backup', models.BooleanField(default=True, help_text='Crear respaldo del PDF original antes de insertar el QR', verbose_name='Habilitar Respaldo de PDF')),
                ('max_pdf_size_mb', models.IntegerField(default=10, help_text='Tamaño máximo permitido para archivos PDF en megabytes', verbose_name='Tamaño Máximo de PDF (MB)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta configuración está activa y debe usarse', verbose_name='Configuración Activa')),
                ('description', models.TextField(blank=True, help_text='Descripción de esta configuración y su propósito', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Procesamiento QR',
                'verbose_name_plural': 'Configuraciones de Procesamiento QR',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='certificate_is_acti_fdaefd_idx'), models.Index(fields=['name'], name='certificate_name_5a82ac_idx')],
            },
        ),
    ]
