# Generated by Django 5.2.7 on 2025-11-02 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_qrprocessingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='available_variables',
            field=models.JSONField(default=list, help_text='Lista de variables que pueden usarse en esta plantilla', verbose_name='Variables Disponibles'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='canvas_height',
            field=models.IntegerField(default=595, help_text='Alto en píxeles (A4 landscape = 595px @ 72dpi)', verbose_name='Alto del Canvas'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='canvas_width',
            field=models.IntegerField(default=842, help_text='Ancho en píxeles (A4 landscape = 842px @ 72dpi)', verbose_name='Ancho del Canvas'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='editor_version',
            field=models.CharField(default='1.0', help_text='Versión del editor con la que se creó/editó', max_length=20, verbose_name='Versión del Editor'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_templates', to=settings.AUTH_USER_MODEL, verbose_name='Último Editor'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='render_config',
            field=models.JSONField(default=dict, help_text='Configuración de DPI, márgenes, calidad, etc.', verbose_name='Configuración de Renderizado'),
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del asset', max_length=200, verbose_name='Nombre')),
                ('asset_type', models.CharField(choices=[('BACKGROUND', 'Fondo'), ('LOGO', 'Logo'), ('SIGNATURE', 'Firma'), ('SEAL', 'Sello'), ('ICON', 'Ícono')], max_length=20, verbose_name='Tipo de Asset')),
                ('file', models.ImageField(help_text='Formatos permitidos: PNG, JPG, JPEG, SVG', upload_to='template_assets/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Archivo')),
                ('category', models.CharField(blank=True, help_text='Categoría para organización (ej: Logos Institucionales, Firmas)', max_length=100, verbose_name='Categoría')),
                ('is_public', models.BooleanField(default=True, help_text='Si es público, estará disponible para todos los usuarios', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Asset de Plantilla',
                'verbose_name_plural': 'Assets de Plantillas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_asset',
            field=models.ForeignKey(blank=True, help_text='Asset de la biblioteca usado como fondo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_using_as_background', to='certificates.templateasset', verbose_name='Asset de Fondo'),
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagen'), ('QR', 'Código QR'), ('LATEX', 'Fórmula LaTeX'), ('VARIABLE', 'Variable Dinámica')], max_length=20, verbose_name='Tipo de Elemento')),
                ('name', models.CharField(help_text='Nombre descriptivo del elemento', max_length=200, verbose_name='Nombre')),
                ('position_x', models.IntegerField(help_text='Posición horizontal en píxeles desde la izquierda', verbose_name='Posición X')),
                ('position_y', models.IntegerField(help_text='Posición vertical en píxeles desde arriba', verbose_name='Posición Y')),
                ('width', models.IntegerField(help_text='Ancho del elemento en píxeles', verbose_name='Ancho')),
                ('height', models.IntegerField(help_text='Alto del elemento en píxeles', verbose_name='Alto')),
                ('rotation', models.FloatField(default=0, help_text='Ángulo de rotación en grados (0-360)', verbose_name='Rotación')),
                ('z_index', models.IntegerField(default=0, help_text='Orden de apilamiento (mayor = más al frente)', verbose_name='Orden Z')),
                ('content', models.TextField(help_text='Texto, código LaTeX, o referencia a asset', verbose_name='Contenido')),
                ('variables', models.JSONField(default=dict, help_text='Variables dinámicas usadas en este elemento', verbose_name='Variables')),
                ('style_config', models.JSONField(default=dict, help_text='Fuente, color, bordes, sombras, etc.', verbose_name='Configuración de Estilo')),
                ('is_locked', models.BooleanField(default=False, help_text='Si está bloqueado, no se puede mover ni editar en el editor', verbose_name='Bloqueado')),
                ('is_visible', models.BooleanField(default=True, help_text='Si está visible en el canvas y en el certificado final', verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('asset', models.ForeignKey(blank=True, help_text='Asset de la biblioteca (para elementos de imagen)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_using', to='certificates.templateasset', verbose_name='Asset')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='certificates.certificatetemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Elemento de Plantilla',
                'verbose_name_plural': 'Elementos de Plantillas',
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='templateasset',
            index=models.Index(fields=['asset_type', 'category'], name='certificate_asset_t_5f28ae_idx'),
        ),
        migrations.AddIndex(
            model_name='templateasset',
            index=models.Index(fields=['is_public', 'created_at'], name='certificate_is_publ_470629_idx'),
        ),
        migrations.AddIndex(
            model_name='templateelement',
            index=models.Index(fields=['template', 'z_index'], name='certificate_templat_4f6e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='templateelement',
            index=models.Index(fields=['element_type'], name='certificate_element_d741df_idx'),
        ),
        migrations.AddIndex(
            model_name='templateelement',
            index=models.Index(fields=['is_visible'], name='certificate_is_visi_fe9f4a_idx'),
        ),
    ]
